version: 2

updates:
  # フロントエンド (npm)
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "yoshihama-nineball"
    labels:
      - "dependencies"
      - "frontend"

  # バックエンド (bundler)
  - package-ecosystem: "bundler"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "10:00"
    open-pull-requests-limit: 5
    reviewers:
      - "yoshihama-nineball"
    labels:
      - "dependencies"
      - "backend"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "11:00"
    reviewers:
      - "yoshihama-nineball"
    labels:
      - "dependencies"
      - "ci"