# backend/config/database.yml
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  # Docker環境の場合
  <% if ENV['DATABASE_URL'].present? %>
  url: <%= ENV['DATABASE_URL'] %>
  <% else %>
  # ローカル環境の場合
  database: angori_development
  username: <%= ENV.fetch('DB_USERNAME', 'postgres') %>
  password: <%= ENV.fetch('DB_PASSWORD', 'password') %>
  host: <%= ENV.fetch('DB_HOST', 'localhost') %>
  port: <%= ENV.fetch('DB_PORT', 5432) %>
  <% end %>

test:
  <<: *default
  database: angori_test
  username: <%= ENV.fetch('DB_USERNAME', 'postgres') %>
  password: <%= ENV.fetch('DB_PASSWORD', 'password') %>
  host: <%= ENV.fetch('DB_HOST', 'localhost') %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>