plugins:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  SuggestExtensions: false
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'config/environments/*'
    - 'bin/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/LineLength:
  Max: 120
  Exclude:
    - 'config/initializers/devise.rb'

# 以下を追加
Metrics/ClassLength:
  Max: 150  # デフォルト100 → 150に変更

Metrics/ModuleLength:
  Max: 150  # デフォルト100 → 150に変更

Metrics/MethodLength:
  Max: 30

Metrics/BlockLength:
  Exclude:
    - 'config/routes.rb'
    - 'spec/**/*'
    - 'config/initializers/*'

Lint/EmptyBlock:
  Exclude:
    - 'spec/factories/*'

# RSpec設定追加
RSpec/MultipleExpectations:
  Max: 6

RSpec/ExampleLength:
  Max: 10

RSpec/NestedGroups:
  Max: 4

RSpec/ContextWording:
  Enabled: false