name: CI

on:
  push:
    branches: [main, develop]

env:
  REGISTRY: ghcr.io

jobs:
  # 前段階の成功確認
  check:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Quality and tests must pass first"

  # Dockerイメージビルド
  build:
    runs-on: ubuntu-latest
    needs: check
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        service: [frontend, backend]

    steps:
    - uses: actions/checkout@v4
    
    - uses: docker/setup-buildx-action@v3
    
    - uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - uses: docker/build-push-action@v5
      with:
        context: ${{ matrix.service }}
        push: true
        tags: ${{ env.REGISTRY }}/${{ github.repository }}-${{ matrix.service }}:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

  # セキュリティスキャン
  security:
    runs-on: ubuntu-latest
    needs: check
    permissions:
      security-events: write

    steps:
    - uses: actions/checkout@v4
    
    - uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        format: 'sarif'
        output: 'trivy-results.sarif'

    - uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'